name: Build and push to GH
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: piriquito/k8s-from-secrets-vault:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}