name: Test Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./docker/Dockerfile
          push: true
          tags: piriquito/k8s-from-secrets-vault:develop
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Install dependencies
        run : go mod download
        working-directory: ./src
      - name: Run tests
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v ./... | go-junit-report -set-exit-code > ../test_report.xml
        working-directory: ./src
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: "**/test_report.xml"
          output: "./test-summary.md"
          show: "all"
        if: always()
      - name: Comment on pull request
        uses: mshick/add-pr-comment@v2
        if: always()
        continue-on-error: true
        with:
          message-path: ./test-summary.md
  integration-test:
    name: Integration Test
    environment: dev
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run test action for configmap
        uses: ./
        with:
          imagelabel: 'develop'
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.NAMESPACE }}
          resource-name: ${{ vars.RESOURCE_NAME }}
          resource-type: 'configmap'
          vault-url: ${{ secrets.VAULT_URL }}
          engine-name: ${{ secrets.SECRET_ENGINE }}
          secret-name: ${{ vars.SECRET_NAME }}
          vault-auth-token: '${{ secrets.VAULT_TOKEN }}'
      - name: Run test action for secrets
        uses: ./
        with:
          imagelabel: 'develop'
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.NAMESPACE }}
          resource-name: ${{ vars.RESOURCE_NAME }}
          resource-type: 'configmap'
          vault-url: ${{ secrets.VAULT_URL }}
          engine-name: ${{ secrets.SECRET_ENGINE }}
          secret-name: ${{ vars.SECRET_NAME }}
          vault-auth-token: '${{ secrets.VAULT_TOKEN }}'