name: Test Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: piriquito/k8s-from-secrets-vault:develop
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install kind
        uses: engineerd/setup-kind@v0.5.0
      - name: Export kubeconfig
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - uses: innovationnorway/setup-vault@v1
        with:
          version: '~1.4'
      - run: vault version
      - name: Run test action
        uses: ./test/
        with:
          kubeconfig: ''
          namespace: ''
          resource-name: ''
          resource-type: ''
          vault-url: ''
          engine-name: ''
          secret-name: ''
          vault-auth-token: ''