name: Test Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: piriquito/k8s-from-secrets-vault:develop
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  test:
    name: Test
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run test action for configmap
        uses: ./
        with:
          imagelabel: 'develop'
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.NAMESPACE }}
          resource-name: ${{ vars.RESOURCE_NAME }}
          resource-type: 'configmap'
          vault-url: ${{ secrets.VAULT_URL }}
          engine-name: ${{ secrets.SECRET_ENGINE }}
          secret-name: ${{ vars.SECRET_NAME }}
          vault-auth-token: '${{ secrets.VAULT_TOKEN }}'
      - name: Run test action for secrets
        uses: ./
        with:
          imagelabel: 'develop'
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.NAMESPACE }}
          resource-name: ${{ vars.RESOURCE_NAME }}
          resource-type: 'configmap'
          vault-url: ${{ secrets.VAULT_URL }}
          engine-name: ${{ secrets.SECRET_ENGINE }}
          secret-name: ${{ vars.SECRET_NAME }}
          vault-auth-token: '${{ secrets.VAULT_TOKEN }}'